### ISSUE TITLE
Two versions of BoxROI

### ISSUE THREAD

**Issue by dequidt** [SofaDefrost/sofa#16]
Hi,

There are two versions of `BoxROI.cpp`

in 

modules/SofaGeneralEngine/BoxROI.cpp
SofaKernel/modules/SofaEngine/BoxROI.cpp

Both seem needed for compilation.

**Comment by damienmarchal** [comment]
It is probably a file move made out of git followed by a merge. 
Can you fix it by keeping the one that is up-to-date and put it at the right location (I don't know what is the right location) ?  Then do a PR :)
